// Explicitly define content collections to silence Astro's auto-detection warning.
// The apparatus YAML file is loaded directly by src/utils/loadApparatus.ts and
// is not a content collection.
// No Astro content collections in this project.
// Apparatus data: src/content/apparatus/de-coloribus.yml (loaded via loadApparatus.ts)
// Text: src/content/de-coloribus.xml (generated by scripts/build-text.ts)
export const collections = {};
